### ISSUE TITLE
Error on cuda path

### ISSUE THREAD

**Issue by Singman33** [krnlx/ccminer-xevan#1]
Hi,
In "configure.sh", you have hardcoded the path of cuda to version 7.5 instead of leaving it to current version.
Should be changed to :
CUDA_CFLAGS="-O3 -lineno -Xcompiler -Wall -D_FORCE_INLINES" ./configure CXXFLAGS="-O3 $extracflags" --with-cuda=/usr/local/cuda --with-nvml=libnvidia-ml.so

**Comment by markusmazurczak** [comment]
The installation path of CUDA depends on the distro you are using. I am using Arch Linux and the default installation path is `/opt/cuda`. That configure.sh is just an helper. You can call configure with all needed parameters by yourself
